name: R-CMD-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-16.04', 'macOS-latest']
        include:
          - os: ubuntu-16.04
            cran: https://demo.rstudiopm.com/all/__linux__/xenial/latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.cran }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          cd TraitMatching
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')" -e "remotes::install_cran('rcmdcheck')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install dependencies
        run: |
          cd TraitMatching
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')" -e "remotes::install_cran('rcmdcheck')"
          Rscript -e "install.packages(c('ranger', 'kknn', 'e1071', 'xgboost'))"
      - name: Check
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(path = 'TraitMatching/', args = '--no-manual', error_on = 'warning', check_dir = 'check')"
