# This is a basic workflow to help you get started with Actions

name: R-CMD-check

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: 
      - master
      - devel
  pull_request:
    branches: 
      - master
      - devel
  schedule:
    - cron: '0 1 * * *'

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-16.04', 'macOS-latest']
        include:
          - os: ubuntu-16.04
            cran: https://demo.rstudiopm.com/all/__linux__/xenial/latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.cran }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          cd TraitMatching
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install dependencies windows
        if: matrix.os == 'windows-latest'
        run: |
          cd TraitMatching
          Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')" -e "install.packages(c('ranger', 'kknn', 'e1071', 'xgboost'), type='binary')"
      - name: Install dependencies linux
        if: ( matrix.os == 'macOS-latest' ) || ( matrix.os == 'ubuntu-16.04' )
        run: |
          cd TraitMatching
          Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')" -e "install.packages(c('ranger', 'kknn', 'e1071', 'xgboost'))"      
      - name: Install Pkg
        run: |
          cd TraitMatching
          Rscript -e "remotes::install_local()"
      - name: Check
        continue-on-error: ${{ contains(matrix.allow_failure, 'true') }}
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(path = 'TraitMatching/', args = '--no-manual', error_on = 'warning', check_dir = 'check')"
